services:
  - type: web
    name: caredesk
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: caredesk-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true